name: CloudReactor AWS ECS Deployer
description: An action to deploy the tasks of a project to AWS ECS and CloudReactor
author: "Machine Intelligence Services, Inc."
branding:
  icon: package
  color: green
inputs:
  aws-access-key-id:
    description: AWS Access Key ID for a user that has deployment privileges
    required: true
  aws-secret-access-key:
    description: AWS Secret Access Key corresponding to the AWS Access Key ID
    required: true
  aws-region:
    description: AWS Region
    required: true
  cloudreactor-api-base-url:
    description: "Base URL for CloudReactor API Service. Defaults to 'https://api.cloudreactor.io' if not defined in your configuration."
    required: false
    default: ""
  cloudreactor-deploy-api-key:
    description: CloudReactor API Key that has Developer access for the Runtime Environment
    required: false
    default: ""
  ansible-vault-password:
    description: Password to decrypt files encrypted with Ansible Vault
    required: false
    default: ""
  extra-ansible-options:
    description: Space-separated list of extra options for Ansible Playbook
    required: false
    default: ""
  deployment-environment:
    description: The name of the deployment environment
    required: true
  version-signature:
    description: "The version signature of the Tasks. Defaults to the commit hash (github.sha)."
    required: false
    default: ${{ github.sha }}
  task-names:
    description: "A comma-separated list of names of Tasks to deploy, or 'ALL' for all Tasks"
    required: false
    default: ALL
  docker-context-dir:
    description: "Path of Docker context directory, relative to the root project directory, without leading or trailing slashes. Defaults to the project root directory."
    required: False
    default: "."
  dockerfile-path:
    description: "Path of the Dockerfile, relative to the root project directory. Defaults to 'Dockerfile' in the Docker context directory."
    required: False
    default: ""
  log-level:
    description: "Log level for deployer"
    required: false
    default: INFO
runs:
  using: docker
  image: docker://ghcr.io/cloudreactor/aws-ecs-cloudreactor-deployer:4.3.2
  env:
    AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
    AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
    DEPLOYMENT_ENVIRONMENT: ${{ inputs.deployment-environment }}
    CLOUDREACTOR_TASK_VERSION_SIGNATURE: ${{ inputs.version-signature }}
    CLOUDREACTOR_API_BASE_URL: ${{ inputs.cloudreactor-api-base-url }}
    CLOUDREACTOR_DEPLOY_API_KEY: ${{ inputs.cloudreactor-deploy-api-key }}
    TASK_NAMES: ${{ inputs.task-names }}
    ANSIBLE_VAULT_PASSWORD: ${{ inputs.ansible-vault-password }}
    EXTRA_ANSIBLE_OPTIONS: ${{ inputs.extra-ansible-options }}
    RELATIVE_DOCKER_CONTEXT_DIR: ${{ inputs.docker-context-dir }}
    RELATIVE_DOCKERFILE_PATH: ${{ inputs.dockerfile-path }}
    CLOUDREACTOR_DEPLOYER_LOG_LEVEL: ${{ inputs.log-level }}
